### ISSUE TITLE
 ERROR OCCURRED SENDING TWEET The remote server returned an error: (401) Unauthorized.

### ISSUE THREAD

**Issue by mkellerman** [CollinChaffin/PSTwitter#1]
Getting:

ERROR OCCURRED SENDING TWEET The remote server returned an error: (401) Unauthorized.

Is there a way to test that my OAuth is working without actually sending a tweet?

**Comment by mkellerman** [comment]
![screen shot 2014-10-26 at 8 40 56 pm](https://cloud.githubusercontent.com/assets/9411143/4786144/f760a392-5d8d-11e4-86a3-7eede284b4cc.png)

**Comment by CollinChaffin** [comment]
Callback cannot be blank.  Fill in both a website URL (a real TLD not .local) and the following for Callback URL:  http://127.0.0.1:3000/auth/twitter/callback

Possible you will need to regenerate token under keys and access tokens and force update of stored values after changing callback URL but otherwise kill all powershell sessions re-import module and retry.

Blank callback URL is #1 reason for 401 unauthorized.

**Comment by mkellerman** [comment]
This code works fine for me... without CallBack url, or website.. :/ 

$status = [System.Uri]::EscapeDataString("My first tweet from Powershell");
$oauth_consumer_key = "<consumer key>";
$oauth_consumer_secret = "<consumer secret>";
$oauth_token = "<auth token>";
$oauth_token_secret = "<auth token secret>";
$oauth_nonce = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes([System.DateTime]::Now.Ticks.ToString()));
$ts = [System.DateTime]::UtcNow - [System.DateTime]::ParseExact("01/01/1970", "dd/MM/yyyy", $null).ToUniversalTime();
$oauth_timestamp = [System.Convert]::ToInt64($ts.TotalSeconds).ToString();

$signature = "POST&";
$signature += [System.Uri]::EscapeDataString("http://api.twitter.com/1/statuses/update.json") + "&";
$signature += [System.Uri]::EscapeDataString("oauth_consumer_key=" + $oauth_consumer_key + "&");
$signature += [System.Uri]::EscapeDataString("oauth_nonce=" + $oauth_nonce + "&"); 
$signature += [System.Uri]::EscapeDataString("oauth_signature_method=HMAC-SHA1&");
$signature += [System.Uri]::EscapeDataString("oauth_timestamp=" + $oauth_timestamp + "&");
$signature += [System.Uri]::EscapeDataString("oauth_token=" + $oauth_token + "&");
$signature += [System.Uri]::EscapeDataString("oauth_version=1.0&");
$signature += [System.Uri]::EscapeDataString("status=" + $status);

$signature_key = [System.Uri]::EscapeDataString($oauth_consumer_secret) + "&" + [System.Uri]::EscapeDataString($oauth_token_secret);

$hmacsha1 = new-object System.Security.Cryptography.HMACSHA1;
$hmacsha1.Key = [System.Text.Encoding]::ASCII.GetBytes($signature_key);
$oauth_signature = [System.Convert]::ToBase64String($hmacsha1.ComputeHash([System.Text.Encoding]::ASCII.GetBytes($signature)));

$oauth_authorization = 'OAuth ';
$oauth_authorization += 'oauth_consumer_key="' + [System.Uri]::EscapeDataString($oauth_consumer_key) + '",';
$oauth_authorization += 'oauth_nonce="' + [System.Uri]::EscapeDataString($oauth_nonce) + '",';
$oauth_authorization += 'oauth_signature="' + [System.Uri]::EscapeDataString($oauth_signature) + '",';
$oauth_authorization += 'oauth_signature_method="HMAC-SHA1",'
$oauth_authorization += 'oauth_timestamp="' + [System.Uri]::EscapeDataString($oauth_timestamp) + '",'
$oauth_authorization += 'oauth_token="' + [System.Uri]::EscapeDataString($oauth_token) + '",';
$oauth_authorization += 'oauth_version="1.0"';

$post_body = [System.Text.Encoding]::ASCII.GetBytes("status=" + $status); 
[System.Net.HttpWebRequest] $request = [System.Net.WebRequest]::Create("http://api.twitter.com/1/statuses/update.json");
$request.Method = "POST";
$request.Headers.Add("Authorization", $oauth_authorization);
$request.ContentType = "application/x-www-form-urlencoded";
$body = $request.GetRequestStream();
$body.write($post_body, 0, $post_body.length);
$body.flush();
$body.close();
$response = $request.GetResponse();

---

Only part i had to change to make it work (Because it was giving the same 401 Unauthorized error) was:

$ts = [System.DateTime]::UtcNow - [System.DateTime]::ParseExact("01/01/1970", "dd/MM/yyyy", $null).ToUniversalTime();

to

$ts = [System.DateTime]::UtcNow - [System.DateTime]::ParseExact("01/01/1970", "dd/MM/yyyy", $null);

**Comment by CollinChaffin** [comment]
Hmm, what timezone are you in I cannot believe that is causing it I have continually been using module to tweet and code you posted is similar enough but fact that you also got 401 and had to make any adjustments tells me something off about your system but it is interesting you were running with no callback url and say you had no issues as that is a common reason for 401.  Are you certain your system is set to proper time zone?  Also, do you have more than 1 twitter application defined so you have possible multiple API keys, etc.?

**Comment by mkellerman** [comment]
Proper time zone? I’m running Windows 7.. and timezone is -8:00 Pacific time (Im in Victoria, BC)

I really dont know what else to do to get it to work.. :/

**Comment by mkellerman** [comment]
And now i’m getting a 403 Forbidden.. and this is from the code that was originally working.

I might be breaking something..

**Comment by CollinChaffin** [comment]
Well 403 can be if you repeat same tweet duplicated I was asking if your timezone is actually set to match so your time is not off.  I'm running out of ideas as it sounds like you had to fidget with UTC time in similar code also producing the 401.  If it were me, I would still create a whole new twitter app with all new API key and tokens after setting it all up with proper website and callback and permissions.  Use the Set-TwitterOAuthTokens -Force to (re)store the new API/tokens and try a simple tweet again.  I have had strange things happen with the Twitter OAuth applications and had to do exactly that then suddenly things worked properly.

I will leave issue open for now until we find a solution but removing UTC time from OAuth noonce should not be necessary.

**Comment by mkellerman** [comment]
Ok, thanks. I'll create another twitter app and see where that goes.

**Comment by mkellerman** [comment]
Ah jeez.. i hate this stuff.. creating another twitter app fixed it.. :/ lol

Thanks! =)

**Comment by CollinChaffin** [comment]
Glad it was sorted!  I've had that happen to me and have never been able to fully explain it! :)
