### ISSUE TITLE
Getting Followers/Friends

### ISSUE THREAD

**Issue by mkellerman** [CollinChaffin/PSTwitter#2]
Is there other resources you could send me to show me how i could modify this code to also pull the list of followers/friends of a twitter user?

**Comment by CollinChaffin** [comment]
I have not had chance to look into building upon it as this was really a ground-up rewrite of another version I had originally forked, but Twitter dev has some good examples.  I will post here and on Twitter when I begin, or feel free to do a pull/fork and begin building on it - that's why it's here for community support!

**Comment by mkellerman** [comment]
I've never used GitHub before.. and would be too scared to break something.. lol

I'm having issues converting your Invoke-RestMethod POST command, into a working GET command:

$httpBody = "screen_name=$fixedFollowing"

Invoke-RestMethod -URI $psTwitterEndpointFollowing -Method Get -Body $httpBody -Headers @{ 'Authorization' = $oAuthRequestString } -ContentType "application/x-www-form-urlencoded" | Out-Null

ERROR: Invoke-RestMethod : Cannot send a content-body with this verb-type.

This is due to having a -Body with a GET method.. 

I tried merging the URI with the httpBody command.. but it simply causes more Auth errors.

Is there a way for me to send you my code so you could take a look?

I think i'm pretty close to getting it to work..

**Comment by mkellerman** [comment]
Ok.. got it to work! =) Mouahahaha.. 

Let me know if you want the updated code.. =)

**Comment by mkellerman** [comment]
Now trying to include the cursor positioning.. :/

**Comment by mkellerman** [comment]
There should be a function that converts the $oAuthRequestString for the Invoke-RestMethod command.. so you don't have to figure out what the problems are when they don't match.. 

But i'm still not fully understanding how these API calls to twitter works.. :/ so it's hard to see my mistakes.

**Comment by mkellerman** [comment]
As soon as i add cursor=-1 to the URI, and to the oAuthSignatureBase, it gives me : 

{"errors":[{"message":"Could not authenticate you","code":32}]}

oAuthSignatureBase =
GET&https%3A%2F%2Fapi.twitter.com%2F1.1%2Ffollowers%2Flist.json&oauth_consumer_key%3DWpjNLrDtv9suRHrFFC8BAzt%26oauth_nonce%3D626KRehwixmGJGjtmZ72xlawsbTHcmAN015C6eC6ZRA1%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1414523693%26oauth_token%3D2840793
927-NHWRTuRtSlH5NxeXAn1y5aGhOiBsKFMxkfDUPkO%26oauth_version%3D1.0%26screen_name%3Dmkellerman%26cursor%3D-1

URI =
https://api.twitter.com/1.1/followers/list.json?screen_name=mkellerman&cursor=-1

If cursor=-1 is not there, everything works good.. and returns me the first 20 followers for mkellerman

**Comment by mkellerman** [comment]
Found the error.. it wasn't sorting the parameters correctly..
